name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        mpi: ['intelmpi']
    steps:
      - uses: actions/checkout@v3
      - uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: build
        run: make cmake
      - uses: actions/upload-artifact@v3
        with:
          name: Output for windows
          path: target
