name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - name: make
      run: make build
    - uses: actions/upload-artifact@v3
      with:
        name: Output for windows
        path: target
