name: Rust

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - uses: KyleMayes/install-llvm-action@v1.6.0
    - name: Build
      run: cargo build --release
